version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: singlesauce-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: singlesauce
      MYSQL_USER: singleuser
      MYSQL_PASSWORD: singlepass
    # Expose MySQL port
    ports:
      - "3306:3306"
    # Persist data between container restarts
    volumes:
      - db_data:/var/lib/mysql
    # If we need to tweak MySQL configuration, custom commands are to be added, e.g.:
    # command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: singlesauce-app
    # image: python:3.12-slim
    environment:
      # Pass environment variables to app
      MyDB_HOST: db
      MyDB_USER: singleuser
      MyDB_PASSWORD: singlepass
      MyDB_DATABASE: singlesauce
      # If we want to test local vs. remote DB
      MyDB_TYPE: mysql
    volumes:
      # Mount local code into the container for live development
      - ./:/usr/src/app
    working_dir: /usr/src/app
    # The main command to run the application.
    command: python kivy_main.py
    # Ensuring the database is available before the app tries to connect
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
    driver: local
